feat(example): 2 new examples
amber-lang/amber-docs pull request #46
Opened 2024-09-12 09:03 UTC by Mte90

I added my script that I use to analyze the shellcheck validation status in Amber using the tests as source and my lsp installer that I used as example for Amber usage (and shellcheck validation).

2024-09-12 12:19 UTC, Ph0enixKM requested changes

2024-09-12 12:19 UTC, Ph0enixKM commented on docs/by_example/lsp_installer.md
For me this example script is pretty lengthy and doesn't highlight the core logic. Can you make a more condensed version that focuses on the most important Amber / stdlib features in action without much repetition?

2024-09-25 21:33 UTC, Ph0enixKM requested changes
Ah.. wrong button... meant to approve it instead

2024-09-25 21:34 UTC, Ph0enixKM approved these changes
It looks alright. Can anyone else review this? If noone has time to do it in the next 12h, you can merge it @Mte90

2024-09-26 10:24 UTC, Mte90 commented
@Ph0enixKM I can't merge it as requires 2 approvals...

2024-09-26 16:18 UTC, merged

2024-09-26 16:18 UTC, Mte90 commented on docs/by_example/lsp_installer.md
> +> The script uses standard library functions to simplify the process of downloading, unpacking, and installing various LSP tools. It checks for necessary permissions, downloads the latest releases of
it is an information box for the website