feat(contribute): migration
amber-lang/amber-docs pull request #47
Opened 2024-09-12 09:14 UTC by Mte90

I migrated the contributing guide from the amber repo and the wiki page in the website (updated some urls).

2024-09-12 13:56 UTC, Ph0enixKM commented
@Mte90 do we want to maintain both the `CONTRIBUTING.md` and the docs `contributing` at the same time?

2024-09-12 13:58 UTC, Mte90 commented
No I think that we will remove that file and in the project readme we put a link to that page in the website.

2024-09-25 21:30 UTC, Ph0enixKM requested changes

2024-09-25 21:30 UTC, Ph0enixKM commented on docs/contribute/contribute.md
> +```
The information about adding build target is obsolete now as we have a CI pipeline that builds the compiler. We can remove this infromation from here.

2024-09-25 21:30 UTC, Ph0enixKM commented on docs/contribute/contribute.md
> +Compile it:
Let's rephrase this.
```suggestion
Compile Amber with the following instructions:
```

2024-09-25 21:30 UTC, Ph0enixKM commented on docs/contribute/internals.md
Instead of calling it "internals" let's call it a "guide_book" or something similar.

2024-09-25 21:30 UTC, Ph0enixKM commented on docs/contribute/internals.md
> +#### 2.3. Built-in creation
```suggestion
#### 2.3. Creating built-ins
```

2024-09-27 16:37 UTC, Ph0enixKM submitted a review, later dismissed
LGTM

2024-09-27 16:50 UTC, hdwalters requested changes

2024-09-27 16:50 UTC, hdwalters commented on docs/contribute/compiler.md
> +```js
Is this JavaScript syntax highlighting?

2024-09-27 16:50 UTC, hdwalters commented on docs/contribute/compiler.md
> +- `syntax_name!("<name of this module>")` that identifies this syntax module with it's name.
Point of trivia: "it's" is short for "it is", not the possessive "its".

2024-09-27 16:50 UTC, hdwalters commented on docs/contribute/compiler.md
> +Parsing returns a `SyntaxResult` that under the hood is represented as `Result<(), Failure>` . It means that parsing can be finished successfully or it can fail returning a `Failure` object.
Please remove space before period.

2024-09-27 16:50 UTC, hdwalters commented on docs/contribute/contribute.md
> +This is a simple but exhaustive guide to get you started on contributing to amber.
Should probably capitalise "Amber" throughout.

2024-09-27 16:50 UTC, hdwalters commented on docs/contribute/contribute.md
> +The way we talk on github is not the same as we would talk in person. When on github, always get straight to the point and be critical.
Should probably capitalise "GitHub" as well.

2024-09-27 16:50 UTC, hdwalters commented on docs/contribute/contribute.md
> +cd Amber
The above `git clone` command will create a subdirectory `amber`, so `cd Amber` will not work on Linux systems.

2024-09-27 16:50 UTC, hdwalters commented on docs/contribute/guide_book.md
> +## Overview
Consider raising the heading level throughout, e.g. changing `##` to `#`, `###` to `##` etc.

2024-09-30 08:16 UTC, Mte90 commented on docs/contribute/compiler.md
> +## Compiler informations
good catch!

2024-09-30 08:18 UTC, Mte90 commented on docs/contribute/compiler.md
> +```js
I guess yes to show the array content

2024-09-30 08:22 UTC, Mte90 commented
@hdwalters I did the various suggestions, about the rust indenting it is something we can fix later.

2024-10-01 10:03 UTC, b1ek approved these changes

2024-10-01 19:13 UTC, hdwalters commented on docs/contribute/contribute.md
> +The way we talk on github is not the same as we would talk in person. When on github, always get straight to the point and be critical.
You still have an uncapitalised "github". Suggest search and replace this throughout the project.

2024-10-01 19:16 UTC, hdwalters requested changes
You still have an uncapitalised "github". Suggest search and replace this throughout the project.

2024-10-02 15:31 UTC, hdwalters submitted a review, later dismissed

2024-10-04 11:48 UTC, Ph0enixKM commented
@Mte90 I tried to change the tabs to 4 spaces but I couldn't collaborate on your branch:
<img width="865" alt="image" src="https://github.com/user-attachments/assets/d363f084-ce95-4c80-8325-1944f7b2553d">

Could you please work on the cloned version of this repository? This way I can collab on the changes. You could try adding me to your fork - perhaps this is a good alternative to it.

2024-10-04 12:46 UTC, Mte90 commented
I fixed the tabs/space situation.

About the access it is very strange as I can access to the other PRs and do changes.

2024-10-05 08:12 UTC, hdwalters approved these changes
The tabs vs spaces debate. Scourge of developers everywhere.

2024-10-15 12:59 UTC, b1ek approved these changes

2024-10-15 13:17 UTC, merged