stdlib(0.4.0): Use the version tag in links
amber-lang/amber-docs pull request #85
Opened 2024-12-27 14:44 UTC by lens0021

2024-12-28 09:31 UTC, Mte90 commented
This pages are generated with amber itself, https://github.com/amber-lang/amber/pull/649/ this PR it was used to do this other PR?

2024-12-28 09:53 UTC, lens0021 commented
> This pages are generated with amber itself, [amber-lang/amber#649](https://github.com/amber-lang/amber/pull/649) this PR it was used to do this other PR?

Absolutely, yes.

2024-12-28 09:59 UTC, Mte90 commented
So it is better to merge the change in amber and after that his one.

2024-12-29 17:55 UTC, Mte90 approved these changes

2025-01-09 21:07 UTC, hdwalters requested changes
Please rerun `amber docs --usage` with the latest version on `staging`.  Now that amber-lang/amber#653 has been merged, (i) the usage examples are not incomplete, and (ii) extra blank lines have been removed from the Markdown.

2025-01-10 23:41 UTC, lens0021 commented
@hdwalters Done. But I have not verified the all newly added links are valid.

2025-01-10 23:56 UTC, lens0021 reviewed
Generating 0.4.0 docs using 0.4.1 is not ideal. What should do?

2025-01-10 23:56 UTC, lens0021 commented on docs/0.4.0-alpha/stdlib/doc/fs.md
> +* [fs_file_glob_relative_with_spaces.ab](https://github.com/amber-lang/amber/blob/0.4.0-alpha/src/tests/stdlib/fs_file_glob_relative_with_spaces.ab)
These links are 404

2025-01-11 09:40 UTC, hdwalters commented
> Generating 0.4.0 docs using 0.4.1 is not ideal. What should do?

Ah, that's a good point, and this was never going to work.  As I see it, we have two choices:

1. Use the official 0.4.0 compiled binary to generate documentation for 0.4.0.
2. Maintain separate documentation for the pre-release version (which will become 0.5.0).

@Ph0enixKM, @Mte90, do you want to weigh in on this?

2025-02-12 09:25 UTC, Mte90 commented
I think that between 0.4.0 and 0.4.1 there wasn't so many changes.
For the future we need to be more careful but we are improving the doc generation so I think that we can merge it in the meantime.

2025-02-16 18:28 UTC, hdwalters reviewed
As previously noted, those Markdown files are generated by the `amber docs` command:
```
hwalters@Ghostwheel ~/git/amber-lang/src/std (main) 
$ amber docs array.ab 
 INFO  File generated at:
/home/hwalters/git/amber-lang/src/std/docs/array.md
```
If you made those URL changes by hand, they'll get overwritten the next time we generate the docs from source again. If we need different URLs here, we need to change the doc generation in the Rust code instead.

2025-02-17 10:33 UTC, Mte90 commented
The changes was already merged in the amber doc generated for the url @hdwalters but we didn't updated the doc after that change. https://github.com/amber-lang/amber/pull/649

2025-02-17 14:16 UTC, hdwalters commented
> The changes was already merged in the amber doc generated for the url @hdwalters but we didn't updated the doc after that change. [amber-lang/amber#649](https://github.com/amber-lang/amber/pull/649)

Derp. I'd forgotten that change. My only excuse is I've had my head full of a different project, and am being a bit slow getting back into Amber mode.

2025-02-17 14:18 UTC, hdwalters approved these changes

2025-02-17 14:42 UTC, merged